#!/bin/sh

BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
bat=/sys/class/power_supply/${BAT}/
per="$(cat "$bat/capacity")"

text() {
	icon=""
	[ $(cat "$bat/status") = Charging ] && icon=""
	echo "$icon $per%"
}

percent() {
	echo $per
}

[ "$1" = "text" ] && text && exit
[ "$1" = "percent" ] && percent && exit
exit
