#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

# if [ -x "/tmp/uhrwerk" ]; then
  # rm /tmp/uhrwerk
# fi

leftwm command "UnloadTheme"

if [ -x "$(command -v eww)" ]; then
	eww kill
fi
pkill compton
pkill picom
pkill eww
# pkill conky
# pkill uhrwerk
