[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[terminal]
shell="/bin/zsh"

[window]
opacity = 0.8

[font]
size = 9.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"
